name: "Go Build Release"
on: push
jobs:
  build:
    name: Build Go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.0
    - name: Make BINS Directory
      shell: bash
      run: mkdir ./bins
    - name: Prep the Go Environment
      shell: bash
      run: |
        wget https://go.dev/dl/go1.20.2.linux-amd64.tar.gz
        sudo rm -rf /usr/local/go
        sudo tar -C /usr/local -xzf go1.20.2.linux-amd64.tar.gz
        export PATH=$PATH:/usr/local/go/bin
    - name: Download Go Modules
      shell: bash
      run: go mod tidy
    - name: OSX Build
      shell: bash
      run: GOOS=darwin GOARCH=amd64 go build -o nfsclient-osx-amd64 nfsclient.go
    - name: Windows x64 Build
      shell: bash
      run: GOOS=windows GOARCH=amd64 go build -o nfsclient-windows-amd64.exe nfsclient.go
    - name: Windows x86 Build
      shell: bash
      run: GOOS=windows GOARCH=386 go build -o nfsclient-windows-x86.exe nfsclient.go
    - name: Linux x64 Build
      shell: bash
      run: GOOS=linux GOARCH=amd64 go build -o nfsclient-linux-amd64 nfsclient.go
    - name: Linux ARM Build
      shell: bash
      run: GOOS=linux GOARCH=arm64 go build -o nfsclient-linux-arm64 nfsclient.go
    - name: Show Directory
      shell: bash
      run: find .
  
